services:
  # 1. Веб-сервис (Django)
  - type: web
    name: myshop-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myshop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromConfig: database_url_from_neon
      - key: REDIS_URL
        fromConfig: redis_url_from_upstash
      - key: DEBUG
        value: False

  # 2. Воркер (Celery)
  - type: worker
    name: myshop-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A myshop worker -l info"
    envVars:
      - key: DATABASE_URL
        fromConfig: database_url_from_neon
      - key: REDIS_URL
        fromConfig: redis_url_from_upstash
